  - defaults:
      link:
        create: true
        relink: true

  - clean: ['~', '~/.config', '$HOMEBREW_PREFIX/bin/cask-upgrade']

  - link:
      $HOMEBREW_PREFIX/bin/cask-upgrade:
        if: '[ "$(uname)" "==" "Darwin" ]'
      ~/.config/alacritty/alacritty.toml:
      ~/.config/nvim/coc-settings.json:
      ~/.config/nvim/init.vim: vimrc
      ~/.config/nvim/utils/format_yaml.py:
      ~/.ctags:
      ~/.dotfiles: ''
      ~/.gitconfig:
      ~/.gitignore:
      ~/.p10k.zsh:
      ~/.ripgreprc:
      ~/.tmux.conf:
      ~/.tmux/tmuxline.conf:
      ~/.vim/coc-settings.json:
      ~/.vimrc:
      ~/.zshrc:
      ~/.zshrc_scripts:
      ~/.zshrc_zplug:
      ~/.Brewfile:
        if: '[ "$(uname)" "==" "Darwin" ]'

  - shell:
      - git submodule sync --recursive
      # the following have to run after linking ~/.gitconfig
      - git submodule update --init --recursive
      - command: ./setup_mac.sh
        description: Install dependecies for Mac
        stdout: true
        stderr: true
      - command: ./python/install_python_tools.sh
        description: Install Python dependecies
        stdout: true
        stderr: true
