- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.config/alacritty/alacritty.yml:
    ~/.ctags:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore:
    ~/.ripgreprc:
    ~/.tmux.conf:
    ~/.tmuxline.conf:
    ~/.vimrc:
    ~/.zshrc:
    ~/.zshrc_scripts:
    ~/.zshrc_zplug:
    ~/.Brewfile:
      if: '[ "$(uname)" "==" "Darwin" ]'

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git submodule update --init --recursive
  - command: ./setup_mac.sh
    description: Install dependecies for Mac
    stdout: true
    stderr: true
