- defaults:
    link:
      create: true
      relink: true

- clean: ['~', '~/.config']

- link:
    ~/.config/alacritty/alacritty.yml:
    ~/.config/nvim/utils/format_yaml.py:
    ~/.ctags:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore:
    ~/.p10k.zsh:
    ~/.ripgreprc:
    ~/.tmux.conf:
    ~/.tmuxline.conf:
    ~/.vim/coc-settings.json:
    ~/.vimrc:
    ~/.zshrc:
    ~/.zshrc_scripts:
    ~/.zshrc_zplug:
    ~/.Brewfile:
      if: '[ "$(uname)" "==" "Darwin" ]'

- pip:
    file: pip/requirements.txt
    user: true    # Like --user
    stdout: true  # Print the execution stdout
    stderr: true  # Print the execution stderr

- shell:
  - git submodule sync --recursive
  # the following have to run after linking ~/.gitconfig
  - git submodule update --init --recursive
  - command: ./setup_mac.sh
    description: Install dependecies for Mac
    stdout: true
    stderr: true
