#!/usr/bin/env bash

# Inspired from: https://gist.github.com/atais/9c72e469b1cbec35c7c430ce03de2a6b

(set -x; brew update;)
(set -x; brew upgrade;)

red=`tput setaf 1`
green=`tput setaf 2`
reset=`tput sgr0`

casks=( $(brew list --cask) )

for cask in ${casks[@]}
do
    versions=$(brew list --cask $cask --versions)
    info=( $(brew info --cask $cask) )
    latest=${info[1]}

    if [[ $versions =~ $latest ]]; then
        echo "${red}${cask}${reset} is ${green}up-to-date${reset}."
    else
        echo "${red}${cask}${reset} requires ${red}update${reset}."
        (set -x; brew install --cask $cask --force --no-quarantine;)
    fi
done

(set -x; brew cleanup;)
